### ISSUE TITLE
Issue with location_name in places with ØÆÅ

### ISSUE THREAD

**Issue by NitraxHub** [wckd/python-yr#35]
First of all, awesome package. Exactly what I'm looking for.

I'm using the branch with python 2 support, and it is working nicely.
However I am having some difficulties getting the weather forecast when I want to get data from places containing Ø,Æ or Å. 

`weather = Yr(location_name='Norge/Rogaland/Hjelmeland/Årdal')`

returns the error 

`'ascii' codec can't decode byte 0xc3 in position 26: ordinal not in range(128)`

Any tips on how to solve this?

Thanks.

**Comment by wckd** [comment]
Thank you for your feedback!
Did you resolve your problem? 
Could you try to add `# -*- coding: utf-8 -*-` at the top of your python file to see if that helps?

**Comment by NitraxHub** [comment]
Unfortunately, I did not. I did try to add that to the top of the file, but with no success. 

However, I have discovered that I have the same issue on some other aspects of my website, which is run on Google App Engine. So it might not be this package at all, but rather GAE's compiler which is acting up.

I don't have time at the moment to look at it again, as the deadline is fast aproaching, but I could try again in a months or so time - when I have all the time in the world

**Comment by phuse** [comment]
Hi,
have similar issue on a debian jessie installation with latest stable release:
  File "now.py", line 8
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xf6 in position 0: invalid start byte


code:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from yr.libyr import Yr
weather = Yr(location_name='Sverige/Blekinge/Hörvik')
now = weather.now()

print(now)

**Comment by wckd** [comment]
Hi!
Thanks for your report, do you still experience this issue?

Regards,
Alexander


10. mar. 2017 3.09 p.m. skrev "Daniel Hrynczenko" <notifications@github.com
>:

Hi,
have similar issue on a debian jessie installation with latest stable
release:
File "now.py", line 8
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xf6 in
position 0: invalid start byte

code:
#!/usr/bin/env python3
-*- coding: utf-8 -*-

from yr.libyr import Yr
weather = Yr(location_name='Sverige/Blekinge/Hörvik')
now = weather.now()

print(now)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/wckd/python-yr/issues/35#issuecomment-285677689>, or mute
the thread
